version: '3'

services:

  web:
    image: mabruras/dock-watch-web:0.1
    build:
      context: web
    restart: unless-stopped
    container_name: dock-watch-web
    labels:
    - "dockwatch.hidden=true"

    environment:
    - "REACT_APP_API_URL=${DOCK_WATCH_API:-http://localhost:5000/api}"
    ports:
    - 3000:3000

  api:
    image: mabruras/dock-watch-api:0.1
    build:
      context: api
    restart: unless-stopped
    container_name: dock-watch-api
    labels:
      - "dockwatch.hidden=true"

    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 5000:5000

  redis:
    image: redis
    restart: unless-stopped
    container_name: dw_redis

    ports:
    - 6379:6379
